### ISSUE TITLE
- [ ] Implementación en el Frontend haciendo uso de ReactJS evidenciando la navegación de acuerdo con los prototipos de alta fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo10_jayg_ppi2020#15]

**Comment by JohnFlorez25** [comment]
@jeferson480 @Yessipinta para dentro de 15 días deben evidenciar avances en esta actividad donde tengan las interfaces en REACTJS de lo que se validó en el prototipo en alta fidelidad y recomendaciones de los jurados en la socialización.
El código debe estar en el repositorio del proyecto (o sea este repositorio) validar con la profesora Derly para que les ayuden a realizar este proceso , les dejo un ejemplo de lo que se debe ir evidenciando.
![evidencia-repositorio](https://user-images.githubusercontent.com/22262727/94869676-6aecfe80-040b-11eb-9bbc-f57f9e86dcc2.jpeg)

**Comment by sofia306** [comment]
https://codesandbox.io/embed/relaxed-field-e1i5e?codemirror=1

Yesica Pérez
Sofia Martinez
