### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo10_jayg_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@jeferson480 @Yessipinta para dentro de 15 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora Derly y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/94869709-7e986500-040b-11eb-935c-3e805ecaab4e.png)

**Comment by sofia306** [comment]
![Cargando IMG_20200917_161126.jpg …]()
Yesica Pérez
Sofia Martinez

**Comment by sofia306** [comment]
Yesica Pérez
Sofia Martinez
![Cargando IMG_20200917_161126.jpg …]()

**Comment by JohnFlorez25** [comment]
@sofia306 @jeferson480 @Yessipinta deben colocarlo en la wiki
