### ISSUE TITLE
- [ ] Diseño del modelo lógico de datos

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo10_jayg_ppi2020#18]

**Comment by sofia306** [comment]
Yesica Pérez
Sofia Martinez
![IMG_20200917_161148.jpg](https://user-images.githubusercontent.com/72270357/95796787-6a7a2080-0cb3-11eb-9cec-adbc420fc1f1.jpg)

**Comment by JohnFlorez25** [comment]
@sofia306 @jeferson480 @Yessipinta deben colocar la evidencia en la wiki
