### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo10_jayg_ppi2020#2]

**Comment by sofia306** [comment]
![IMG-20201006-WA0000.jpg](https://user-images.githubusercontent.com/72270357/95215554-b5c59800-07b6-11eb-98ba-a4b1b8a60674.jpg)

Sofia Martinez Rodríguez y
Yesica Pérez Roqueme
